### ISSUE TITLE
STARs funktionieren teilweise

### ISSUE THREAD

**Issue by jakobeng1303** [lachsschinken124/atc#12]
der command `star` geht jetzt zb `star mabod.mabod4n.loww` leider setzt sich die Geschwindigkeit auf 450+ Knoten. Bug oder so und die altitude restrictions gehen irgendwie noch nicht. Mal sehen. Vielleicht sollten wir die 34 als test runway nehmen und die altitude restrictions schon früher strikter setzen und testen

**Comment by lachsschinken124** [comment]
Solved with `dvs`.
