### ISSUE TITLE
Fixes wie RW 11 als Ende der Star hinzufügen?

### ISSUE THREAD

**Issue by jakobeng1303** [lachsschinken124/atc#19]
hätte den Vorteil, dass die Flieger wirklich bis zur Piste auf Kurs bleiben (sollte man die Landeerlaubnis vergessen

**Comment by jakobeng1303** [comment]
RW 11 ist der Fix am Anfang der 11

**Comment by lachsschinken124** [comment]
Ja, kann man testen

**Comment by lachsschinken124** [comment]
Solved in 9601a5c

**Comment by jakobeng1303** [comment]
Danke!
